AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function is triggered off an upload to a bucket. It logs the content type of the uploaded object.
Parameters:
  Handler:
    Type: String
  Runtime:
    Type: String
  S3CodeBucket:
    Type: String
  S3CodeKey:
    Type: String
  BucketListener:
    Type: String
  FilterPrefix:
    Type: String
  Timeout:
    Type: String
    Default: 30


Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: !Ref Handler
      Runtime: !Ref Runtime
      Timeout: !Ref Timeout
      CodeUri:
        Bucket: !Ref S3CodeBucket
        Key: !Ref S3CodeKey
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:Get*
                - s3:List*
              Resource: !Join ["", ["arn:aws:s3:::", !Ref Bucket, "/*"]]
            - Effect: Allow
              Action:
                - acm:Describe*
              Resource: "*"
      Events:
        EmailArrival:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*

  Bucket:
    Type: AWS::S3::Bucket
    BucketName: cert-approvals
    LifecycleConfiguration:
      Rules:
        - Id: DeleteStuff
          Status: Enabled
          ExpirationInDays: 30
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 'ses.amazonaws.com'
            Action:
              - 's3:PutObject'
            Resource: !Join ["", ["arn:aws:s3:::", !Ref Bucket, "/*"]]
            Condition:
              StringEquals:
                "aws:Referer": !Sub ${AWS::AccountId}
